feat: added crude method of checking all running containers

diff --git a/vserver/hetzner/management/roles/docker/files/healthcheck_docker b/vserver/hetzner/management/roles/docker/files/healthcheck_docker
--- a/vserver/hetzner/management/roles/docker/files/healthcheck_docker
+++ b/vserver/hetzner/management/roles/docker/files/healthcheck_docker
@@ -3,14 +3,27 @@
 HOST=$(hostname)
 LIST="
 "
+RUNNING=$(docker ps --format "{{.Names}}" | sort | grep -v watchtower)
+
 for i in $LIST; do
 	docker container exec $i sh 2>/dev/null;
 	if [ $? != 0 ] ; then
 		export FAILED="$FAILED $i"
 	fi
 done
+for i in $RUNNING; do
+	docker container exec $i sh 2>/dev/null;
+	if [ $? != 0 ] ; then
+		export FAILED2="$FAILED2 $i"
+	fi
+done
 
 if [ ${FAILED+x} ]  ; then
 	echo "$FAILED down" | mail -s "$HOST Status $(date +%d.%m.%Y) " $HOST@REDACTED
 	echo "$FAILED down"
+fi
+
+if [ ${FAILED2+x} ]  ; then
+	echo "$FAILED2 down" | mail -s "$HOST Status $(date +%d.%m.%Y) " $HOST@REDACTED
+	echo "$FAILED2 down"
 fi
